---
version: 2.1

orbs:
  python: broadinstitute/bits-python@0.2.0
workflows:
  test_deploy:
    jobs:
      - python/run-tests:
          name: tests
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
          version: '3.7'
      - python/deploy:
          version: '3.7'
          context: pypi
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          requires: [tests]
