---
version: 2.1

orbs:
  python: broadinstitute/bits-python@0.2.0
workflows:
  test_deploy:
    jobs:
      - python/run-tests:
          name: tests-3-4
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
          version: '3.4'
      - python/run-tests:
          name: tests-3-5
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
          version: '3.5'
      - python/run-tests:
          name: tests-3-6
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
          version: '3.6'
      - python/run-tests:
          name: tests-3-7
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
          version: '3.7'
      - python/run-tests:
          name: tests-3-8
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
          version: '3.8.0rc1'
      - python/deploy:
          version: '3.7'
          verify_tag: false
          context: pypi
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          requires: [tests-3-4, tests-3-5, tests-3-6, tests-3-7, tests-3-8]
