version: 2.1

tag_filter: &tag_filter
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

orbs:
  python: broadinstitute/bits-python@0.2.0
workflows:
  test_and_deploy:
    jobs:
      - python/preflight:
          version: '3.7'
      - python/run-tests:
          version: '3.7'
      - python/deploy:
          version: '3.7'
          context: pypi
          <<: [*tag_filter]
