name: check format

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '.github/workflows/black.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '.github/workflows/black.yml'

jobs:
  black:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: black style
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3.5.3
      - name: setting up python
        uses: actions/setup-python@v4.7.1
        with:
          python-version-file: pyproject.toml
      - name: check python formatting using black
        uses: rickstaa/action-black@v1.3.1
        id: action_black
      - name: creating pull request
        if: steps.action_black.outputs.is_formatted == 'true' && github.head_ref == ''
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          commit-message: 'style(format): reformat with black'
          title: 'style(format): reformat with black'
          body: |
            This pull requests deploys the new Python code style [black][1].
            [1]: https://github.com/psf/black
          labels: |
            style
            chore
            black
          branch: black
          delete-branch: true
          branch-suffix: short-commit-hash
      - name: annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true' && github.head_ref != ''
        uses: reviewdog/action-suggester@v1.7.5
        with:
          tool_name: blackfmt
