name: check black

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '**/poetry.lock'
      - '**/pyproject.toml'
      - '**/black.yml'
  pull_request_target:
    branches: [ main ]
    paths:
      - '**.py'
      - '**/poetry.lock'
      - '**/pyproject.toml'

jobs:
  black:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-latest]
    name: check black style
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: setting up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2.1.4
        with:
          python-version: ${{ matrix.python-version }}
      - name: "set pip cache dir"
        run: echo "::set-env name=pip-cache::$(pip cache dir)"
      - name: caching pip storage
        uses: actions/cache@v2.1.8
        with:
          path: ${{ env.pip-cache }}
          key: ${{ runner.os }}-${{ matrix.python-version }}-black-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-black-${{ hashFiles('**/poetry.lock') }}
            ${{ runner.os }}-${{ matrix.python-version }}-black
      - name: installing black
        run: pip install black
      - name: running black
        run: black --target-version py38 .
      - name: creating pull request
        if: ${{ github.head_ref == '' }}
        uses: peter-evans/create-pull-request@v3.4.1
        with:
          commit-message: 'style(format): reformat with black'
          title: 'Update black code style'
          body: |
            This pull requests deploys the new Python code style [black][1].
            [1]: https://github.com/psf/black
          labels: |
            style
            chore
            black
          branch: black
      - name: committing changed files
        if: ${{ github.head_ref != '' }}
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: 'style(format): reformat with black'
          branch: ${{ github.head_ref }}
          file_pattern: '*.py'
