name: black

on:
  pull_request:
    paths:
      - '**.py'

jobs:
  black:
    runs-on: ubuntu-latest
    name: enforce black
    steps:
      - uses: actions/checkout@v1
      - name: setting up python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: installing black
        run: pip install black
      - name: running black
        run: black --target-version py37 .
      - name: committing changed files
        uses: stefanzweifel/git-auto-commit-action@v2.4.0
        with:
          commit_message: 'chore(style): enforce black'
          branch: ${{ github.head_ref }}
          file_pattern: '*.py'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
