name: enforce black

on:
  pull_request_target:
    paths:
      - '**.py'

jobs:
  black:
    runs-on: ubuntu-latest
    name: enforce black
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          ref: ${{ github.head_ref }}
      - name: setting up python
        uses: actions/setup-python@v2.1.2
        with:
          python-version: '3.7'
      - name: "set pip cache dir"
        run: echo "::set-env name=pip-cache::$(pip cache dir)"
      - name: caching pip storage
        uses: actions/cache@v2.1.1
        with:
          path: ${{ env.pip-cache }}
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ matrix.python-version }}-pip
      - name: installing black
        run: pip install black
      - name: running black
        run: black --target-version py37 .
      - name: committing changed files
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          commit_message: 'style(format): enforce black'
          branch: ${{ github.head_ref }}
          file_pattern: '*.py'
