name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    environment: publishing
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3.5.3
      - name: setting up python
        uses: actions/setup-python@v4.7.1
        with:
          python-version-file: pyproject.toml
      - name: install and configure poetry
        uses: pronovic/setup-poetry@v1.2.0
        with:
          version: 1.5.1
          plugins: poetry-git-version-plugin
      - name: install dependencies
        run: poetry install -n -vv --all-extras
      - name: running tests
        run: poetry run green -vv
      - name: write package version
        run: poetry git-version
      - name: build with git version
        run: poetry build -n -vv
      - name: generate coverage xml
        run: poetry run coverage xml
      - name: uploading coverage to codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
      - name: generate mint token
        id: mint
        uses: tschm/token-mint-action@v1.0.2
      - name: publishing to PyPi
        run: poetry publish -n -vv -u __token__ -p '${{ steps.mint.outputs.api-token }}'
