name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    environment: publishing
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        python-version: [3.8]
        poetry-version: [1.5.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3.5.3
      - name: setting up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: setting up poetry ${{ matrix.poetry-version }}
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install dependencies
        run: poetry install -n -vv --all-extras
      - name: running tests
        run: poetry run green -vv
      - name: install poetry git version plugin
        run: poetry self add poetry-git-version-plugin
      - name: write package version
        run: poetry git-version
      - name: build with git version
        run: poetry build -n -vv
      - name: generate coverage xml
        run: poetry run coverage xml
      - name: uploading coverage to codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: python ${{ matrix.python-version }} on ${{ runner.os }}
      - name: generate mint token
        id: mint
        uses: tschm/token-mint-action@v1.0.2
      - name: publishing to PyPi
        run: poetry publish -n -vv -u __token__ -p '${{ steps.mint.outputs.api-token }}'
